### ISSUE TITLE
Will this Arduino-FOC support STM32 Nuceo-144 development board?

### ISSUE THREAD

**Issue by nonlinear1** [simplefoc/Arduino-FOC#106]
Dear All
   Could someone know whether Arduino-FOC support  STM32 Nuceo-144 development board with STM32H755ZI MCU or not? And this MCU support Arduino.
Thank you very much!

**Comment by askuric** [comment]
Hey @nonlinear1,

We are having plans to support the Aruduino portenta H7 boards which have very similar CPU as the nucleo-144.
In the mean time, since we are using a very generic stm32 implementation,  I'd encourage you to test board already with the current library version. The chances are that major parts of the code will work already.

If you do test it, please do let us know about your findings :D
It will make us advance in this topic faster!
