### ISSUE TITLE
TCC0 pin config ATSAME51

### ISSUE THREAD

**Issue by Juanduino** [simplefoc/Arduino-FOC#122]
Hi

There is some bug in the /drivers/hardware_specific/samd51_mcu.cpp

See this log: https://community.simplefoc.com/t/same51-pin-configuration/1280/3

Attached variant.cpp:
https://github.com/adafruit/ArduinoCore-samd/blob/master/variants/feather_m4_can/variant.cpp

According to the variant file pin 13, 12, 11, 10 are PIN_ATTR_PWM_G

There seems to be some confusion in the appropriate function when fetchin pin configuration. 

I would like to setup pins 13, 12, 11 and 10 for TCC0. Plz advice

Is the Peripheral letter used for configuring pin?

Here the samd_mcu.cpp is supposed to fin a "G" ?

```
#if defined(_SAMD51_)||defined(_SAME51_)
	else if (peripheral==PIO_TCC_PDEC) {
		result.tcc.chaninfo = association.tccG;
		result.wo = association.woG
```;

**Comment by Juanduino** [comment]
I did a bit of re-arranging on the wiring_analog file 

```
#if defined(__SAMD51__) || defined(_SAME51_) 
  Adc *adc;
  if(g_APinDescription[pin].ulPinAttribute & PIN_ATTR_ANALOG) adc = ADC0;
 
  else if(g_APinDescription[pin].ulPinAttribute & PIN_ATTR_ANALOG_ALT) adc = ADC1;

  else return 0;
  
  if (adc == ADC0) {
	  SUPC->VREF.reg |= SUPC_VREF_TSEN | SUPC_VREF_ONDEMAND;
  GCLK->PCHCTRL[ADC0_GCLK_ID].reg = GCLK_PCHCTRL_GEN_GCLK1_Val | (1 << GCLK_PCHCTRL_CHEN_Pos);
  }
  if (adc == ADC1) {
	  SUPC->VREF.reg |= SUPC_VREF_TSEN | SUPC_VREF_ONDEMAND;
  GCLK->PCHCTRL[ADC1_GCLK_ID].reg = GCLK_PCHCTRL_GEN_GCLK1_Val | (1 << GCLK_PCHCTRL_CHEN_Pos);
  }
	  
  adc->CTRLA.bit.PRESCALER = ADC_CTRLA_PRESCALER_DIV4_Val; 
  while( adc->SYNCBUSY.reg & ADC_SYNCBUSY_CTRLB );
  adc->CTRLB.bit.RESSEL = ADC_CTRLB_RESSEL_12BIT_Val;
  
  while (adc->SYNCBUSY.reg & ADC_SYNCBUSY_CTRLB); //wait for sync
  adc->SAMPCTRL.reg = 0;   
  while( adc->SYNCBUSY.reg & ADC_SYNCBUSY_SAMPCTRL ); //wait for sync
// Averaging (see datasheet table in AVGCTRL register description)
		adc->AVGCTRL.reg = ADC_AVGCTRL_SAMPLENUM_1 |    // 1 sample only (no oversampling nor averaging)
							ADC_AVGCTRL_ADJRES(0x0ul);   // Adjusting result by 0

		while( adc->SYNCBUSY.reg & ADC_SYNCBUSY_AVGCTRL );  //wait for sync
  

  while( adc->SYNCBUSY.reg & ADC_SYNCBUSY_INPUTCTRL ); //wait for sync
  adc->INPUTCTRL.bit.MUXPOS = g_APinDescription[pin].ulADCChannelNumber; // Selection for the positive ADC input
```

**Comment by runger1101001** [comment]
Ok, I have fixed the SAMD51 pin assignment issue, I believe.
But I think you may still not get what you want as described above.

The issue had to do with the peripheral E/F/G selection and assignment. Basically it was using E when it should have been using G, and in SAMD51 the TC units (on E) don't even get configured by the code, so it wasn't working at all.

But now this is fixed, and in my tests it correctly selects pins on peripheral F or G (or a mix thereof) according to its pin-selection algorithm.

However, this still does not mean you will get peripheral G for pins 10,11,12... this is because they also have a valid (and equal or better) configuration on TCC1, peripheral F. And since all you can specify via the API is the pin numbers, there is no way for the driver code to know you might prefer G.
The auto-selection algorithm will pick the "best" available configuration though - preferring to keep pins on the same TCC unit for example...

The fixed code is merged to the dev branch of SimpleFOC, you could test it if you like.

**Comment by runger1101001** [comment]
Fixed in https://github.com/simplefoc/Arduino-FOC/pull/134
