### ISSUE TITLE
Stepper motor closed loop control doesn't seem to work

### ISSUE THREAD

**Issue by stignarnia** [simplefoc/Arduino-FOC#232]
**Describe the bug**
I tried running this example and it didn't work, despite using basically the same hardware: https://github.com/simplefoc/simplefoc.github.io/blob/28b483510cb9b5b22fd640fdac20aeeaa71a6483/docs/simplefoc_library/examples/stepper_control_nucleo.md

**Describe the hardware setup**
For us it is very important to know what is the hardware setup you're using in order to be able to help more directly
- NEMA 14 hybrid stepper motor with 4 wires
- L298N driver
- STM32 nucleo board (tried multiple SKUs)
- Analog magnetic sensor (did change the example code to use the appropriate class)
- Current sensing used? No

**IDE you are using**
- Platformio

**Comment by runger1101001** [comment]
First question: in your platformio.ini, do you have the option `lib_archive = false` ? This is important when working with SimpleFOC in PlatformIO...

Other than this, I would suggest you pose this question in our forums. Here on GitHub we tend to deal with specific bug reports, e.g. that relate specifically to the code. For problems related to setup / hardware / software configuration we advise to ask questions on the forum, where other users can read it and may be able to help.

My suspicion is, assuming everything else is configured correctly, that the precision of the analog sensor / ADC may be a problem. Stepper motors usually have high pole counts. If the error on the analog sensor is large, it will be too large of an electrical angle due to the high pole count, and good control will be impossible.

Have you investigated the precision and linearity of the analog sensor setup?
